version: "3"

networks:
   app-network:
      driver: bridge

services:
   app-client:
      build: .
      ports:
         - "8080:8080"
      environment:
         SPRING_DATA_MONGODB_HOST: ${SPRING_DATA_MONGODB_HOST:-mongo}
         SPRING_DATA_MONGODB_PORT: ${SPRING_DATA_MONGODB_PORT:-27017}
         SPRING_DATA_MONGODB_DATABASE: ${SPRING_DATA_MONGODB_DATABASE:-cliente}
         SPRING_DATA_MONGODB_USERNAME: ${SPRING_DATA_MONGODB_USERNAME:-root}
         SPRING_DATA_MONGODB_PASSWORD: ${SPRING_DATA_MONGODB_PASSWORD:-root}
         SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:-admin}
      depends_on:
         - mongo
      networks:
         - app-network

   mongo:
      image: mongo:latest
      ports:
         - "27017:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
         MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      networks:
         - app-network
